services:
  - type: web
    name: app-ordenes-compra
    runtime: node
    plan: free
    buildCommand: npm install && npm run db:generate:render && npm run build
    startCommand: npm run start:render
    healthCheckPath: /api/orders
    envVars:
      - key: NODE_ENV
        value: production
      - key: TAX_RATE
        value: "0.21"
      - key: DATABASE_URL
        sync: false
