import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Boxes, Check, ChevronDown, Package, Search, SlidersHorizontal } from 'lucide-react';

const money = (value, currency = 'ARS') => { try { return new Intl.NumberFormat('es-AR', { style: 'currency', currency, maximumFractionDigits: 0 }).format(Number(value)); } catch { return `${currency} ${Number(value).toLocaleString('es-AR')}`; } };
export default function Catalog({ onCreateOrder }) {
  const [items, setItems] = useState([]); const [query, setQuery] = useState(''); const [category, setCategory] = useState('Todas'); const [stockOnly, setStockOnly] = useState(false); const [loading, setLoading] = useState(true); const [mobileFilters, setMobileFilters] = useState(false);
  useEffect(() => { fetch('/api/items').then((r) => r.json()).then(setItems).finally(() => setLoading(false)); }, []);
  const categories = useMemo(() => ['Todas', ...new Set(items.map((item) => item.categoria).filter(Boolean))], [items]);
  const filtered = items.filter((item) => { const text = `${item.codigo} ${item.descripcion} ${item.marca || ''}`.toLowerCase(); return text.includes(query.toLowerCase()) && (category === 'Todas' || item.categoria === category) && (!stockOnly || Number(item.stockActual) > 0); });
  return <div className="page-stack">
    <section className="catalog-header"><span className="eyebrow dark">Catálogo corporativo</span><h1>Encontrá el material indicado.</h1><p>Consultá stock, compará proveedores y elegí la mejor opción para tu próxima compra.</p><label className="catalog-search"><Search/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por nombre, código o marca…"/><kbd>⌘ K</kbd></label></section>
    <div className="catalog-toolbar"><div><strong>{filtered.length}</strong> productos encontrados</div><button className="filter-toggle" onClick={() => setMobileFilters(!mobileFilters)}><SlidersHorizontal size={17}/> Filtros <ChevronDown size={16}/></button><select aria-label="Ordenar productos"><option>Más relevantes</option><option>Menor precio</option><option>Mayor stock</option></select></div>
    <div className="catalog-layout">
      <aside className={`filters-panel ${mobileFilters ? 'open' : ''}`}><div><h2>Filtros</h2><button onClick={() => {setCategory('Todas');setStockOnly(false);}}>Limpiar</button></div><fieldset><legend>Categoría</legend>{categories.map((name) => <label key={name}><input type="radio" name="category" checked={category === name} onChange={() => setCategory(name)}/><span>{name}</span></label>)}</fieldset><fieldset><legend>Disponibilidad</legend><label><input type="checkbox" checked={stockOnly} onChange={(e) => setStockOnly(e.target.checked)}/><span>Solo con stock</span></label></fieldset></aside>
      <section className="product-grid" aria-live="polite">{loading ? Array.from({length:6}).map((_,i) => <div className="product-card skeleton" key={i}/>) : filtered.length ? filtered.map((item) => { const best = [...(item.ofertas || [])].sort((a,b) => Number(a.precioConIva)-Number(b.precioConIva))[0]; const inStock = Number(item.stockActual) > 0; return <article className="product-card" key={item.id}><div className="product-image"><Package size={48}/><span className={inStock ? 'stock-badge' : 'stock-badge warning'}>{inStock ? <><Check size={13}/> En stock</> : 'A reponer'}</span></div><div className="product-info"><span className="product-code">{item.codigo} · {item.categoria || 'General'}</span><h2>{item.descripcion}</h2><p>{[item.marca, item.unidadMedida].filter(Boolean).join(' · ') || 'Material de compra'}</p><div className="product-meta"><span>Stock <strong>{Number(item.stockActual)} {item.unidadMedida || 'u.'}</strong></span><span>Proveedores <strong>{item.ofertas?.length || 0}</strong></span></div><div className="product-footer"><div><small>{best ? 'Mejor precio con IVA' : 'Precio de referencia'}</small><strong>{money(best?.precioConIva ?? item.precioUnitario, best?.moneda)}</strong></div><button onClick={onCreateOrder} aria-label={`Comprar ${item.descripcion}`}><ArrowRight/></button></div></div></article>; }) : <div className="empty-catalog"><Boxes/><h2>No encontramos productos</h2><p>Probá con otra búsqueda o quitá algunos filtros.</p></div>}</section>
    </div>
  </div>;
}
