import { useEffect, useState } from 'react';

const LABELS = { BORRADOR: 'Borrador', ENVIADA: 'Enviada', APROBADA: 'Aprobada', RECIBIDA: 'Recibida', CANCELADA: 'Cancelada' };
const money = new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 });
export default function Dashboard() {
  const [data, setData] = useState({ bySupplier: [], byStatus: [] }); const [error, setError] = useState('');
  useEffect(() => { fetch('/api/reports/purchases').then((r) => r.ok ? r.json() : Promise.reject()).then(setData).catch(() => setError('No se pudieron cargar los reportes.')); }, []);
  const maxSupplier = Math.max(...data.bySupplier.map((x) => x.total), 1); const maxStatus = Math.max(...data.byStatus.map((x) => x.cantidad), 1);
  return <div className="grid gap-6 lg:grid-cols-2">{error && <p className="text-red-600">{error}</p>}<section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-1 text-lg font-semibold">Compras por proveedor</h2><p className="mb-5 text-sm text-slate-500">Monto total de órdenes no canceladas.</p><div className="space-y-4">{data.bySupplier.length ? data.bySupplier.sort((a,b) => b.total-a.total).map((x) => <div key={x.nombre}><div className="mb-1 flex justify-between gap-4 text-sm"><span className="truncate font-medium">{x.nombre}</span><span>{money.format(x.total)}</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${(x.total / maxSupplier) * 100}%` }}/></div></div>) : <p className="text-sm text-slate-500">Aún no hay órdenes para graficar.</p>}</div></section><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-1 text-lg font-semibold">Órdenes según estado</h2><p className="mb-5 text-sm text-slate-500">Cantidad de órdenes activas por situación.</p><div className="space-y-4">{data.byStatus.length ? data.byStatus.map((x) => <div key={x.estado}><div className="mb-1 flex justify-between text-sm"><span className="font-medium">{LABELS[x.estado] || x.estado}</span><span>{x.cantidad} orden{ x.cantidad !== 1 ? 'es' : '' }</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${(x.cantidad / maxStatus) * 100}%` }}/></div><p className="mt-1 text-right text-xs text-slate-500">{money.format(x.total)}</p></div>) : <p className="text-sm text-slate-500">Aún no hay órdenes para graficar.</p>}</div></section></div>;
}
