import { useEffect, useState } from 'react';
import { CheckCircle2, ChevronDown, ChevronUp, Download, FileSpreadsheet, FileText, Plus, Save, Trash2, Upload, XCircle } from 'lucide-react';
import * as XLSX from 'xlsx';

const today = () => new Date().toISOString().slice(0, 10);
const emptyOffer = () => ({ proveedorId:'', nombreProveedor:'', codigoProveedor:'', marcaProveedor:'', esPreferido:false, precioSinIva:'', precioConIva:'', moneda:'ARS', fechaActualizacionCosto:today(), tiempoEntrega:'', loteMinimo:1 });
const empty = () => ({ codigo:'', descripcion:'', marca:'', categoria:'', familia:'', subfamilia:'', estado:'ACTIVO', unidadMedida:'', unidadCompra:'', factorConversion:1, codigoQr:'', puntoPedido:'', stockMaximo:'', ubicacion:'', costoEstandar:'', iva:21, atributosTecnicos:'', documentacionUrl:'', ofertas:[emptyOffer()] });
const currencies = ['ARS','USD','EUR','BRL','CLP','UYU'];
const units = ['Unidad','kg','g','t','l','ml','m','cm','m²','m³','Pack','Caja','Rollo','Placa'];
const Section = ({ title, subtitle, children }) => <section className="material-section"><div className="material-section-title"><div><h3>{title}</h3><p>{subtitle}</p></div></div>{children}</section>;
const Input = ({ label, ...props }) => <label className="label">{label}<input {...props} className="field mt-1" /></label>;

export default function Materials() {
  const [materials,setMaterials] = useState([]); const [suppliers,setSuppliers] = useState([]); const [form,setForm] = useState(empty()); const [editing,setEditing] = useState(null); const [message,setMessage] = useState(''); const [showForm,setShowForm] = useState(false);
  const [showImport,setShowImport] = useState(false); const [importRows,setImportRows] = useState([]); const [importErrors,setImportErrors] = useState([]); const [importing,setImporting] = useState(false); const [updateExisting,setUpdateExisting] = useState(false); const [importFile,setImportFile] = useState('');
  const load = () => Promise.all([fetch('/api/items'),fetch('/api/suppliers')]).then(async ([i,s]) => { setMaterials(await i.json()); setSuppliers(await s.json()); });
  useEffect(() => { load(); }, []);
  const change = (e) => setForm({...form,[e.target.name]:e.target.value});
  const changeOffer = (index,key,value) => setForm((current) => ({...current,ofertas:current.ofertas.map((offer,i) => { if(i!==index)return offer; if(key==='precioSinIva') return {...offer,precioSinIva:value,precioConIva:value===''?'':(Number(value)*1.21).toFixed(2)}; if(key==='esPreferido' && value) return {...offer,esPreferido:true}; return {...offer,[key]:value}; }).map((offer,i) => key==='esPreferido'&&value&&i!==index?{...offer,esPreferido:false}:offer)}));
  const reset = () => { setForm(empty()); setEditing(null); setShowForm(false); };
  const submit = async (e) => { e.preventDefault(); setMessage(''); const response = await fetch(editing?`/api/items/${editing}`:'/api/items',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,ofertas:form.ofertas.filter((o)=>o.proveedorId)})}); const data=await response.json().catch(()=>({})); if(!response.ok)return setMessage(data.error||'No se pudo guardar el material.'); setMessage('Material guardado correctamente.'); reset(); load(); };
  const edit = (m) => { setEditing(m.id); setShowForm(true); setForm({...empty(),...m,stockMaximo:m.stockMaximo??'',ofertas:m.ofertas.length?m.ofertas.map((o)=>({...emptyOffer(),...o,precioSinIva:Number(o.precioSinIva),precioConIva:Number(o.precioConIva),loteMinimo:Number(o.loteMinimo||1),fechaActualizacionCosto:o.fechaActualizacionCosto?.slice(0,10)||''})):[emptyOffer()]}); window.scrollTo({top:0,behavior:'smooth'}); };
  const remove = async (id) => { if(!window.confirm('¿Eliminar este material?'))return; const response=await fetch(`/api/items/${id}`,{method:'DELETE'}); if(!response.ok)return setMessage((await response.json()).error); load(); };

  const normalizeHeader = (value) => String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
  const aliases = { codigo:['codigo','codigointerno','sku'], descripcion:['descripcion','nombre','material'], marca:['marca'], categoria:['categoria'], familia:['familia'], subfamilia:['subfamilia'], estado:['estado'], unidadMedida:['unidad','unidadmedida','unidadprincipal'], stockActual:['stock','stockactual'], puntoPedido:['puntopedido','stockminimo','reorden'], stockMaximo:['stockmaximo'], ubicacion:['ubicacion','almacen'], costoEstandar:['costo','costoestandar','precio'], iva:['iva','ivaporcentaje'], unidadCompra:['unidadcompra'], factorConversion:['factorconversion'], codigoQr:['codigoqr','qr'], atributosTecnicos:['atributostecnicos','atributos'], documentacionUrl:['documentacionurl','documentacion','url'] };
  const pick = (row, names) => { const key=Object.keys(row).find((candidate)=>names.includes(normalizeHeader(candidate))); return key==null?'':row[key]; };
  const numericFields = ['stockActual','puntoPedido','stockMaximo','costoEstandar','iva','factorConversion'];
  const parseImport = async (event) => { const file=event.target.files?.[0]; if(!file)return; setMessage(''); setImportFile(file.name); setImportRows([]); setImportErrors([]); try { const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'}); const sheet=workbook.Sheets[workbook.SheetNames[0]]; const raw=XLSX.utils.sheet_to_json(sheet,{defval:''}); if(!raw.length)throw new Error('La primera hoja no contiene datos.'); const seen=new Set(); const errors=[]; const rows=raw.map((source,index)=>{const row={sourceRow:index+2};Object.entries(aliases).forEach(([field,names])=>{row[field]=pick(source,names)});row.codigo=String(row.codigo||'').trim();row.descripcion=String(row.descripcion||'').trim();row.estado=String(row.estado||'ACTIVO').trim().toUpperCase();numericFields.forEach((field)=>{if(row[field]!==''&&row[field]!=null)row[field]=Number(row[field])});if(!row.codigo)errors.push({row:index+2,error:'Falta el código.'});if(!row.descripcion)errors.push({row:index+2,error:'Falta la descripción.'});if(!['ACTIVO','INACTIVO','DESCONTINUACION'].includes(row.estado))errors.push({row:index+2,error:'Estado inválido. Usá ACTIVO, INACTIVO o DESCONTINUACION.'});if(seen.has(row.codigo))errors.push({row:index+2,error:`Código repetido en el archivo: ${row.codigo}.`});seen.add(row.codigo);numericFields.forEach((field)=>{if(row[field]!==''&&(!Number.isFinite(row[field])||row[field]<0))errors.push({row:index+2,error:`${field} debe ser un número positivo.`})});return row});setImportRows(rows);setImportErrors(errors); } catch(error){setImportErrors([{row:'—',error:error.message||'No se pudo leer el archivo.'}])} event.target.value=''; };
  const runImport = async () => { if(!importRows.length||importErrors.length)return;setImporting(true);setMessage('');try{const response=await fetch('/api/items/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows:importRows,updateExisting})});const result=await response.json();if(!response.ok)throw new Error(result.error);const summary=`Importación finalizada: ${result.created} creados, ${result.updated} actualizados, ${result.skipped} omitidos${result.errors.length?` y ${result.errors.length} rechazados`:''}.`;setMessage(summary);setImportErrors(result.errors||[]);if(!result.errors.length){setImportRows([]);setImportFile('');setShowImport(false)}load()}catch(error){setMessage(error.message||'No se pudo importar la planilla.')}finally{setImporting(false)}};
  const downloadTemplate = () => { const csv='Codigo,Descripcion,Categoria,Marca,Unidad,Stock actual,Punto de pedido,Stock maximo,Ubicacion,Costo estandar,IVA\nMAT-001,Material de ejemplo,General,,Unidad,0,0,,Deposito,0,21\n';const link=document.createElement('a');link.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));link.download='plantilla-materiales.csv';link.click();URL.revokeObjectURL(link.href); };

  return <div className="page-stack materials-page">
    <header className="module-header"><div><span className="eyebrow dark">Maestro corporativo</span><h1>Materiales</h1><p>Un nombre interno y todas las equivalencias necesarias por proveedor.</p></div><div className="module-actions"><button className="btn-secondary" onClick={()=>{setShowImport(!showImport);setShowForm(false)}}><Upload size={17}/> Importar Excel</button><button className="btn-primary" onClick={()=>{setShowForm(!showForm);setShowImport(false)}}>{showForm?<ChevronUp/>:<Plus/>}{showForm?'Cerrar ficha':'Nuevo material'}</button></div></header>
    {message&&<p className="notice">{message}</p>}
    {showImport&&<section className="import-panel"><div className="import-heading"><div><FileSpreadsheet/><div><h2>Importar materiales</h2><p>Archivos Excel o CSV, hasta 1.000 filas. La primera fila debe contener los encabezados.</p></div></div><button className="btn-secondary" onClick={downloadTemplate}><Download size={16}/> Descargar plantilla</button></div><div className="import-drop"><input id="materials-import" type="file" accept=".xlsx,.xls,.csv" onChange={parseImport}/><label htmlFor="materials-import"><Upload/><strong>Seleccionar planilla</strong><span>.xlsx, .xls o .csv</span></label>{importFile&&<p>Archivo: <strong>{importFile}</strong></p>}</div>{importRows.length>0&&<><div className="import-summary"><span><CheckCircle2/> {importRows.length} filas leídas</span><span className={importErrors.length?'has-errors':''}>{importErrors.length?<><XCircle/> {importErrors.length} errores</>:<><CheckCircle2/> Lista para importar</>}</span><label><input type="checkbox" checked={updateExisting} onChange={e=>setUpdateExisting(e.target.checked)}/> Actualizar materiales existentes con el mismo código</label></div><div className="import-preview"><table><thead><tr><th>Fila</th><th>Código</th><th>Descripción</th><th>Categoría</th><th>Unidad</th><th>Stock</th><th>Estado</th></tr></thead><tbody>{importRows.slice(0,50).map(row=><tr key={row.sourceRow} className={importErrors.some(e=>Number(e.row)===row.sourceRow)?'invalid':''}><td>{row.sourceRow}</td><td>{row.codigo||'—'}</td><td>{row.descripcion||'—'}</td><td>{row.categoria||'—'}</td><td>{row.unidadMedida||'—'}</td><td>{row.stockActual===''?'0':row.stockActual}</td><td>{row.estado}</td></tr>)}</tbody></table>{importRows.length>50&&<p>Se muestran las primeras 50 filas.</p>}</div></>}{importErrors.length>0&&<div className="import-errors"><strong>Corregí estos datos antes de continuar:</strong>{importErrors.slice(0,20).map((error,index)=><p key={`${error.row}-${index}`}>Fila {error.row}: {error.error}</p>)}</div>}<div className="form-actions"><button className="btn-secondary" onClick={()=>{setShowImport(false);setImportRows([]);setImportErrors([])}}>Cancelar</button><button className="btn-primary" disabled={!importRows.length||Boolean(importErrors.length)||importing} onClick={runImport}>{importing?'Importando…':`Importar ${importRows.length||''} materiales`}</button></div></section>}
    {showForm&&<form onSubmit={submit} className="material-form">
      <div className="form-heading"><div><FileText/><div><h2>{editing?'Editar ficha':'Nueva ficha de material'}</h2><p>Los campos internos se usan para inventario; las equivalencias se imprimen en la OC.</p></div></div><button className="btn-primary"><Save size={17}/>{editing?'Guardar cambios':'Crear material'}</button></div>
      <Section title="A. Datos generales e identificación" subtitle="Denominación única utilizada por tu empresa."><div className="form-grid four"><Input required label="Código interno / SKU *" name="codigo" value={form.codigo} onChange={change}/><Input required label="Nombre / descripción interna *" name="descripcion" value={form.descripcion} onChange={change}/><Input label="Categoría" name="categoria" value={form.categoria||''} onChange={change}/><label className="label">Estado<select name="estado" value={form.estado} onChange={change} className="field mt-1"><option value="ACTIVO">Activo</option><option value="INACTIVO">Inactivo</option><option value="DESCONTINUACION">En descontinuación</option></select></label><Input label="Familia" name="familia" value={form.familia||''} onChange={change}/><Input label="Subfamilia" name="subfamilia" value={form.subfamilia||''} onChange={change}/><label className="label">Unidad principal<select name="unidadMedida" value={form.unidadMedida||''} onChange={change} className="field mt-1"><option value="">Seleccionar</option>{units.map(u=><option key={u}>{u}</option>)}</select></label><Input label="Marca interna" name="marca" value={form.marca||''} onChange={change}/></div></Section>
      <Section title="B. Matriz de proveedores asociados" subtitle="Agregá tantos proveedores y nombres equivalentes como necesites."><div className="offer-list">{form.ofertas.map((o,index)=><article className="offer-row" key={index}><div className="offer-number">Proveedor {index+1}{o.esPreferido&&<span>Preferido</span>}</div><div className="form-grid four"><label className="label">Proveedor<select className="field mt-1" value={o.proveedorId} onChange={(e)=>changeOffer(index,'proveedorId',e.target.value)}><option value="">Seleccionar</option>{suppliers.map(s=><option value={s.id} key={s.id}>{s.nombre}</option>)}</select></label><Input label="Código del proveedor" value={o.codigoProveedor||''} onChange={(e)=>changeOffer(index,'codigoProveedor',e.target.value)}/><Input label="Nombre exacto del proveedor" value={o.nombreProveedor||''} onChange={(e)=>changeOffer(index,'nombreProveedor',e.target.value)}/><Input label="Marca / fabricante" value={o.marcaProveedor||''} onChange={(e)=>changeOffer(index,'marcaProveedor',e.target.value)}/><Input type="number" min="0" step=".01" label="Precio sin IVA" value={o.precioSinIva} onChange={(e)=>changeOffer(index,'precioSinIva',e.target.value)}/><label className="label">Moneda<select className="field mt-1" value={o.moneda} onChange={(e)=>changeOffer(index,'moneda',e.target.value)}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label><Input type="number" min="0" label="Lead time (días)" value={o.tiempoEntrega??''} onChange={(e)=>changeOffer(index,'tiempoEntrega',e.target.value)}/><Input type="number" min="0" step=".01" label="Lote mínimo (MOQ)" value={o.loteMinimo??1} onChange={(e)=>changeOffer(index,'loteMinimo',e.target.value)}/></div><footer><label><input type="radio" name="preferido" checked={Boolean(o.esPreferido)} onChange={()=>changeOffer(index,'esPreferido',true)}/> Proveedor habitual / preferido</label><button type="button" disabled={form.ofertas.length===1} onClick={()=>setForm({...form,ofertas:form.ofertas.filter((_,i)=>i!==index)})}><Trash2 size={16}/> Quitar</button></footer></article>)}</div><button type="button" className="btn-secondary mt-4" onClick={()=>setForm({...form,ofertas:[...form.ofertas,emptyOffer()]})}><Plus size={16}/> Asociar otro proveedor</button></Section>
      <Section title="C. Stock y reabastecimiento" subtitle="Parámetros para alertas y planificación."><div className="form-grid four"><Input type="number" min="0" step=".01" label="Stock mínimo / reorden" name="puntoPedido" value={form.puntoPedido??''} onChange={change}/><Input type="number" min="0" step=".01" label="Stock máximo" name="stockMaximo" value={form.stockMaximo??''} onChange={change}/><Input label="Ubicación en almacén" name="ubicacion" value={form.ubicacion||''} onChange={change}/><Input label="Código QR" name="codigoQr" value={form.codigoQr||''} onChange={change}/></div></Section>
      <Section title="D. Costos y conversión" subtitle="Valores de referencia para análisis y consumo."><div className="form-grid four"><Input type="number" min="0" step=".01" label="Costo estándar / reposición" name="costoEstandar" value={form.costoEstandar??''} onChange={change}/><Input type="number" min="0" max="100" step=".01" label="IVA aplicable (%)" name="iva" value={form.iva??21} onChange={change}/><label className="label">Unidad de compra<select name="unidadCompra" value={form.unidadCompra||''} onChange={change} className="field mt-1"><option value="">Igual a unidad principal</option>{units.map(u=><option key={u}>{u}</option>)}</select></label><Input type="number" min=".0001" step=".0001" label="Factor de conversión" name="factorConversion" value={form.factorConversion??1} onChange={change}/></div></Section>
      <Section title="E. Ficha técnica y documentación" subtitle="Información técnica y enlaces a documentos."><div className="form-grid two"><label className="label">Atributos técnicos<textarea name="atributosTecnicos" value={form.atributosTecnicos||''} onChange={change} rows="4" className="field mt-1" placeholder="Espesor, densidad, color, acabado, dimensiones…"/></label><label className="label">URL de ficha técnica / documentación<textarea name="documentacionUrl" value={form.documentacionUrl||''} onChange={change} rows="4" className="field mt-1" placeholder="Enlace a PDF, plano, certificado o MSDS"/></label></div></Section>
      <div className="form-actions"><button type="button" className="btn-secondary" onClick={reset}>Cancelar</button><button className="btn-primary"><Save size={17}/> Guardar material</button></div>
    </form>}
    <section className="materials-list"><div className="list-heading"><div><h2>Materiales registrados</h2><p>{materials.length} fichas en el maestro interno</p></div></div>{materials.length?materials.map(m=><article className="material-card" key={m.id}><div className="material-main"><span className={`status-dot ${m.estado?.toLowerCase()||'activo'}`}>{m.estado||'ACTIVO'}</span><h3>{m.codigo} · {m.descripcion}</h3><p>{[m.categoria,m.familia,m.subfamilia,m.marca].filter(Boolean).join(' › ')||'Sin clasificación'}</p><div className="material-stats"><span>Stock <strong>{Number(m.stockActual)} {m.unidadMedida||'u.'}</strong></span><span>Reorden <strong>{Number(m.puntoPedido||0)}</strong></span><span>Ubicación <strong>{m.ubicacion||'—'}</strong></span></div></div><div className="material-actions"><button onClick={()=>edit(m)}>Editar</button><button className="danger" onClick={()=>remove(m.id)}><Trash2 size={17}/></button></div><div className="equivalence-grid">{m.ofertas.map(o=><div key={o.id}><small>{o.proveedor.nombre}{o.esPreferido?' · Preferido':''}</small><strong>{o.codigoProveedor||m.codigo}</strong><p>{o.nombreProveedor||m.descripcion}</p><span>{o.moneda} {Number(o.precioSinIva).toLocaleString('es-AR')} · {o.tiempoEntrega??'—'} días</span></div>)}</div></article>):<div className="empty-catalog"><FileText/><h2>Todavía no hay materiales</h2><p>Creá la primera ficha para comenzar.</p></div>}</section>
  </div>;
}
