import { useEffect, useState } from 'react';
import { ArrowDownToLine, ArrowUpFromLine } from 'lucide-react';

export default function Stock() {
  const [items, setItems] = useState([]); const [form, setForm] = useState({ productoId: '', tipo: 'ENTRADA', cantidad: 1, motivo: '' }); const [message, setMessage] = useState('');
  const load = () => fetch('/api/stock').then((r) => r.json()).then(setItems);
  useEffect(() => { load(); }, []);
  const submit = async (e) => { e.preventDefault(); setMessage(''); const res = await fetch('/api/stock/movements', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, productoId: Number(form.productoId), cantidad: Number(form.cantidad) }) }); const data = await res.json(); if (!res.ok) return setMessage(data.error); setMessage('Movimiento registrado.'); setForm({ productoId: '', tipo: 'ENTRADA', cantidad: 1, motivo: '' }); load(); };
  return <div className="space-y-6"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-1 text-lg font-semibold">Registrar movimiento de stock</h2><p className="mb-4 text-sm text-slate-500">Las órdenes marcadas como “Recibida” ingresan sus unidades automáticamente.</p><form onSubmit={submit} className="grid gap-3 md:grid-cols-4"><select required value={form.productoId} onChange={(e) => setForm({ ...form, productoId: e.target.value })} className="field"><option value="">Producto</option>{items.map((i) => <option key={i.id} value={i.id}>{i.codigo} — {i.descripcion}</option>)}</select><select value={form.tipo} onChange={(e) => setForm({ ...form, tipo: e.target.value })} className="field"><option value="ENTRADA">Entrada</option><option value="SALIDA">Salida</option><option value="AJUSTE">Ajuste positivo</option></select><input required min="0.01" step="0.01" type="number" value={form.cantidad} onChange={(e) => setForm({ ...form, cantidad: e.target.value })} className="field" placeholder="Cantidad"/><div className="flex gap-2"><input value={form.motivo} onChange={(e) => setForm({ ...form, motivo: e.target.value })} className="field" placeholder="Motivo"/><button className="btn-primary">Registrar</button></div></form>{message && <p className="mt-3 text-sm text-blue-700">{message}</p>}</section><section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><h2 className="border-b border-slate-200 p-5 text-lg font-semibold">Existencias actuales</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Código</th><th className="p-3">Producto</th><th className="p-3 text-right">Stock actual</th><th className="p-3 text-right">Mínimo</th><th className="p-3">Situación</th></tr></thead><tbody>{items.map((item) => { const low = Number(item.stockActual) <= Number(item.stockMinimo); return <tr key={item.id} className="border-t border-slate-100"><td className="p-3 font-medium">{item.codigo}</td><td className="p-3">{item.descripcion}</td><td className="p-3 text-right">{Number(item.stockActual)}</td><td className="p-3 text-right">{Number(item.stockMinimo)}</td><td className="p-3"><span className={low ? 'rounded-full bg-red-100 px-2.5 py-1 text-xs font-semibold text-red-700' : 'rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-semibold text-emerald-700'}>{low ? 'Reponer' : 'Disponible'}</span></td></tr>; })}</tbody></table></div></section></div>;
}
