import { useEffect, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';

const empty = { nombre: '', taxId: '', email: '', telefono: '', direccion: '' };
export default function Suppliers() {
  const [suppliers, setSuppliers] = useState([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(null); const [message, setMessage] = useState('');
  const load = () => fetch('/api/suppliers').then((r) => r.json()).then(setSuppliers);
  useEffect(() => { load(); }, []);
  const change = (e) => setForm({ ...form, [e.target.name]: e.target.value });
  const submit = async (e) => { e.preventDefault(); setMessage(''); const res = await fetch(editing ? `/api/suppliers/${editing}` : '/api/suppliers', { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await res.json().catch(() => ({})); if (!res.ok) return setMessage(data.error || 'No se pudo guardar.'); setForm(empty); setEditing(null); setMessage('Proveedor guardado correctamente.'); load(); };
  const edit = (supplier) => { setEditing(supplier.id); setForm({ nombre: supplier.nombre, taxId: supplier.taxId, email: supplier.email || '', telefono: supplier.telefono || '', direccion: supplier.direccion || '' }); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const remove = async (id) => { if (!window.confirm('¿Eliminar este proveedor?')) return; const res = await fetch(`/api/suppliers/${id}`, { method: 'DELETE' }); if (!res.ok) { const data = await res.json(); return setMessage(data.error); } load(); };
  return <div className="grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={submit} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-semibold">{editing ? 'Editar proveedor' : 'Nuevo proveedor'}</h2>{[['nombre','Nombre *'],['taxId','CUIT / Tax ID *'],['email','Email'],['telefono','Teléfono'],['direccion','Dirección']].map(([key,label]) => <label key={key} className="label">{label}<input required={key === 'nombre' || key === 'taxId'} name={key} value={form[key]} onChange={change} className="field mt-1" /></label>)}<div className="mt-5 flex gap-2"><button className="btn-primary"><Plus size={16}/>{editing ? 'Guardar' : 'Agregar'}</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm(empty); }} className="btn-secondary">Cancelar</button>}</div>{message && <p className="mt-3 text-sm text-blue-700">{message}</p>}</form><section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><h2 className="border-b border-slate-200 p-5 text-lg font-semibold">Proveedores registrados</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Nombre</th><th className="p-3">CUIT</th><th className="p-3">Contacto</th><th className="p-3"/></tr></thead><tbody>{suppliers.map((s) => <tr key={s.id} className="border-t border-slate-100"><td className="p-3 font-medium">{s.nombre}</td><td className="p-3">{s.taxId}</td><td className="p-3">{s.email || s.telefono || '—'}</td><td className="p-3 text-right"><button onClick={() => edit(s)} className="mr-2 text-blue-700">Editar</button><button onClick={() => remove(s.id)} aria-label="Eliminar proveedor" className="text-red-600"><Trash2 size={17}/></button></td></tr>)}</tbody></table></div></section></div>;
}
