const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]);
const show = (value) => escapeHtml(value || '—');
const date = (value) => value ? new Date(value).toLocaleDateString('es-AR') : '—';

export async function generatePurchaseOrderPdf(orderId) {
  const popup = window.open('', '_blank');
  if (!popup) throw new Error('El navegador bloqueó la ventana del PDF. Habilite las ventanas emergentes e intente nuevamente.');
  popup.document.write('<p style="font-family:Arial;padding:24px">Preparando orden de compra...</p>');
  try {
    const response = await fetch(`/api/orders/${orderId}`);
    if (!response.ok) throw new Error('No se pudo cargar la orden.');
    const order = await response.json();
    const currency = order.moneda || 'ARS';
    const money = (value) => { try { return new Intl.NumberFormat('es-AR', { style: 'currency', currency }).format(Number(value)); } catch { return `${escapeHtml(currency)} ${Number(value).toFixed(2)}`; } };
    const itemRows = order.items.map((line) => `<tr><td>${show(line.producto.codigo)}</td><td>${show(line.producto.descripcion)}</td><td class="num">${show(Number(line.cantidad))}</td><td class="num">${money(line.precioUnitario)}</td><td class="num">${money(line.subtotalLinea)}</td></tr>`).join('');
    popup.document.open();
    popup.document.write(`<!doctype html><html lang="es"><head><meta charset="utf-8"><title>${escapeHtml(order.numeroOrden)} - Besten-Rodner Ingeniería SRL</title><style>
      @page{size:A4;margin:13mm}*{box-sizing:border-box}body{font:11px Arial,sans-serif;color:#172033;margin:0}h1,h2,p{margin:0}.header{display:flex;justify-content:space-between;border-bottom:3px solid #1d4ed8;padding-bottom:12px;margin-bottom:14px}.brand h1{font-size:21px;color:#1d4ed8}.brand p{margin-top:4px}.order{text-align:right}.order h2{font-size:19px}.order strong{display:block;font-size:15px;margin:5px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:10px 0}.box{border:1px solid #cbd5e1;border-radius:5px;padding:9px;break-inside:avoid}.box h2{font-size:11px;text-transform:uppercase;color:#1d4ed8;margin-bottom:7px}.line{margin:3px 0;white-space:pre-wrap}.label{font-weight:bold}table{width:100%;border-collapse:collapse;margin:12px 0;page-break-inside:auto}th{background:#eaf0ff;text-align:left}th,td{border:1px solid #cbd5e1;padding:6px}tr{page-break-inside:avoid}.num{text-align:right}.totals{margin-left:auto;width:43%;break-inside:avoid}.totals div{display:flex;justify-content:space-between;padding:4px 6px}.totals .grand{border-top:2px solid #172033;font-size:14px;font-weight:bold;margin-top:3px;padding-top:7px}.wide{margin:10px 0}.signature{margin-top:26px;display:grid;grid-template-columns:1fr 1fr;gap:50px;text-align:center}.signature div{border-top:1px solid #172033;padding-top:5px}.actions{position:fixed;right:16px;top:16px}@media print{.actions{display:none}}@media screen{body{max-width:900px;margin:24px auto;padding:20px;box-shadow:0 0 12px #bbb}}
    </style></head><body><button class="actions" onclick="window.print()">Imprimir / Guardar PDF</button>
      <header class="header"><div class="brand"><h1>Besten-Rodner Ingeniería SRL</h1><p>CUIT 30-71461916-7</p><p>Vera Mujica 3440, Rosario, Santa Fe</p></div><div class="order"><h2>ORDEN DE COMPRA</h2><strong>${escapeHtml(order.numeroOrden)}</strong><p>Fecha de emisión: ${date(order.fechaEmision)}</p></div></header>
      <div class="grid"><section class="box"><h2>Datos del comprador</h2><p class="line"><span class="label">Razón social:</span> Besten-Rodner Ingeniería SRL</p><p class="line"><span class="label">CUIT:</span> 30-71461916-7</p><p class="line"><span class="label">Dirección:</span> Vera Mujica 3440, Rosario, Santa Fe</p></section><section class="box"><h2>Datos del proveedor</h2><p class="line"><span class="label">Razón social:</span> ${show(order.proveedorRazonSocial || order.proveedor.nombre)}</p><p class="line"><span class="label">Identificación fiscal:</span> ${show(order.proveedorTaxId || order.proveedor.taxId)}</p><p class="line"><span class="label">Contacto:</span> ${show(order.proveedorContacto)}</p><p class="line"><span class="label">Dirección:</span> ${show(order.proveedorDireccion)}</p><p class="line"><span class="label">Email / teléfono:</span> ${show(order.proveedorDatosContacto)}</p></section></div>
      <div class="grid"><section class="box"><h2>Entrega</h2><p class="line"><span class="label">Fecha esperada:</span> ${date(order.fechaEntregaEsperada)}</p><p class="line"><span class="label">Lugar:</span> ${show(order.lugarEntrega)}</p><p class="line"><span class="label">Envío / transporte:</span> ${show(order.metodoEnvio)}</p></section><section class="box"><h2>Pago y facturación</h2><p class="line"><span class="label">Moneda:</span> ${show(currency)}</p><p class="line"><span class="label">Condiciones:</span> ${show(order.condicionesPago)}</p><p class="line"><span class="label">Dirección de facturación:</span> ${show(order.direccionFacturacion)}</p></section></div>
      <table><thead><tr><th>Código</th><th>Descripción</th><th class="num">Cantidad</th><th class="num">Precio unitario</th><th class="num">Total</th></tr></thead><tbody>${itemRows}</tbody></table>
      <section class="totals"><div><span>Subtotal</span><strong>${money(order.subtotal)}</strong></div><div><span>Impuestos / IVA (${Number(order.porcentajeImpuestos)}%)</span><strong>${money(order.impuestos)}</strong></div><div><span>Descuentos</span><strong>− ${money(order.descuentos)}</strong></div><div class="grand"><span>Total a pagar</span><span>${money(order.total)}</span></div></section>
      <section class="box wide"><h2>Notas adicionales</h2><p class="line">${show(order.observaciones)}</p></section><section class="box wide"><h2>Términos y condiciones</h2><p class="line">${show(order.terminosCondiciones)}</p></section>
      <div class="signature"><div><strong>${show(order.autorizadoPor)}</strong><br>Persona autorizada</div><div><strong>${show(order.firmaAutorizacion)}</strong><br>Firma / autorización</div></div>
      <script>setTimeout(() => window.print(), 350)</script></body></html>`);
    popup.document.close();
  } catch (error) { popup.close(); throw error; }
}
